name: open_hands
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  font_awesome_flutter: ^10.5.0
  flutter_rating_bar: ^4.0.1
  http: ^1.1.0
  camera: ^0.10.5+3
  path_provider: ^2.1.0
  path: ^1.8.3
  #  For image representation
  card_swiper: ^3.0.1
  cached_network_image: ^3.2.1
  uuid: ^3.0.7
  phone_form_field: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # ensures that the Material Icons font is included with your application
  uses-material-design: true
  # To add assets to your application
  # https://flutter.dev/assets-and-images/#resolution-aware
  # https://flutter.dev/assets-and-images/#from-packages
  assets:
    - assets/images/
    - assets/hotel/ # TODO delete after setup